### ISSUE TITLE
Add support to select a different fragment cache backend per StorageRouter

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework-alba-plugin#125]
Add support to select a different fragment cache backend per StorageRouter.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/521
https://github.com/openvstorage/framework-alba-plugin/pull/126

**Comment by wimpers** [comment]
@kvanhijf anything to do for this one?

**Comment by kvanhijf** [comment]
No, everything's fixed related to this
Closing...
