### ISSUE TITLE
GUI hangs for 2s when rendering ALBA backend detail page

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#162]
GUI hangs for 2s when rendering ALBA backend detail page

**Comment by khenderick** [comment]
So far it looks like we don't do anything stupid, but that this is just the time it takes for the GUI to render.

**Comment by khenderick** [comment]
Assume it takes 5 seconds to render the disks (for e.g. 20 nodes). This means each node needs about 250ms to render. During this rendering, the browser page does not respond (e.g. no scrolling, no changes on the page).

Currently: this not responding will take 5 seconds, after that, everything works smooth again.
Option: render the nodes one by one, with e.g. 500ms delay. However, this means that the browser will be semi unresponsive during 15 seconds (250ms unresponsive, 500ms responsive, 250ms unresponsive, ...)

**Comment by wimpers** [comment]
Leave it like it is in that case
