### ISSUE TITLE
md member devices can be used as a backend disk (rendering the md device useless)

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework-alba-plugin#171]
md member devices can be used as a backend disk (rendering the md device useless)

**Comment by wimpers** [comment]
@khenderick didn't you make some changes around this when updating the code to make the disks selection in storagerouters and asd nodes similar? Still an issue?

**Comment by wimpers** [comment]
Relates to https://github.com/openvstorage/framework-alba-plugin/issues/169

**Comment by khenderick** [comment]
@wimpers, no as #169 is not yet handled.

**Comment by kvanhijf** [comment]
Most likely fixed by https://github.com/openvstorage/framework/issues/792

**Comment by wimpers** [comment]
Closed by PM.
