### ISSUE TITLE
Make the backend detail page more clear

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#172]
Currently the backend detail page of a backend is unclear in case you have many node in the cluster.

Thing to make the page more clean and easier to use:
- add a show 'All nodes' button under the ASD nodes tab
-  By default hide nodes which don't offer disks which are used by the backend (toggle the All nodes to show all nodes in the cluster)
- If the disk is initialized but can't be used as the disks is claimed, add a green border to the disk instead of filling the disk with a green color
- remove green from the list of other backend colors

**Comment by khenderick** [comment]
Suggestion; Sort nodes by used/unused and collapse "unused" nodes. Then we can just use the currently available collapsing functionality.

**Comment by wimpers** [comment]
If unused means unused by the backend (the one you  selected), fine.

**Comment by wimpers** [comment]
Since the ticket with the AD the nodes are by default collapsed. This ticket has since then become obsolete. Create a ticket in case new changes are needed to the backend page.
![2017-09-12_15-23-04.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55a79589ac2b010e00797421/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2b8ed7cf508bdc67a0b77276b48e13b628ae92dbc56395b4d5a49ac145d5645faf0dd78f4be3426825c0be5806c5d7dc22f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e78e8d4d3c19071988fd5f27ed.jpg)
