### ISSUE TITLE
maintenance process placement is rather sub awesome for local backend in a multi datacenter ovs cluster

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework-alba-plugin#177]
I noticed on the OVH env that maintenance for the hdd-grav backend was running on some of the roubaix nodes (and no maintenance process on any node of the gravelin datacenter).
When set up like this you lose local repair, all data has to travel back and forth between the datacenters...

**Comment by khenderick** [comment]
The maintenance process distribution was designed as "foreach backend, run a maintenance process on _all_ storage nodes until you met the required amount of maintenance processes". The code doesn't know about datacenters, so it doesn't care about the placement.

A solution would be to prefer nodes that have disks claimed to the backend.

**Comment by domsj** [comment]
When do you deploy maintenance processes?
Probably immediately when setting up a backend ... so that's when it doesn't have disks yet.
So then you would either have to delay deploying maintenance processes, or move the maintenance processes in some sort of periodic checkup once disks have been claimed?

**Comment by khenderick** [comment]
Valid point, we currently have a function that will validate the current maintenance processes and remove/add some if required. We can extend this so it can basically move them around, and call it more frequently (now it's only when you set up a backend or add a new node).

**Comment by khenderick** [comment]
After some talking with @domsj, we could take it further and start adding a meaning to the domain tags assigned to a backend. We can add these domains to nodes as well, and prefer to have maintenance processes in the same domain. We can even start to assign roles to nodes.

**Comment by khenderick** [comment]
@wimpers, this ticket was suddenly qualified, which option do you want to be implemented?
* My suggestion using the claimed disks to make an educated guess
* @domsj's suggestion to assign meaning to Domains wrt Alba Backends, configure them on Nodes and do assignment like that
* @domsj's suggestion to inplement a role system on the backend ("maintenance role")

**Comment by wimpers** [comment]
@kenneth assign meaning to Domains wrt Alba Backends, configure them on Nodes and do assignment like that.

**Comment by khenderick** [comment]
For a global backend using only remote backends this is an issue, as they don't have any nodes on which to run the maintenance mode.

**Comment by khenderick** [comment]
Fixed by #202, packaged in openvstorage-backend-1.7.3-rev.694.f9f958c

**Comment by kinvaris** [comment]
Will verify this next week during reinstall/upgrade of OVH environment.

**Comment by kinvaris** [comment]
On OVH we see indeed that the maintenance agents are placed in the respective datacenters. Although these are only 2 sites where we observed this.
