### ISSUE TITLE
Make backend creation more flexible

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#178]
Currently the creation of a backend is quite hardcoded to deploy the arakoon dbs on the master nodes. Another option is to deploy the abm and nsm arakoons manually but that requires you create the arakoons clusters one by one.

I see 2 possibilities to make the backend creation more flexible.
-  In the create backend step allow to select the abm and nsm arakoon from a list (only show unused arakoons). We should have the list of arakoons in etcd. In this case the user creates all arakoons in advance in one go (push the arakoon setup step to ansible). (In the future we could allow to manage the arakoons from the GUI (create, extend, shrink) from the administration section like we extend the vpools). 
- In the create backend step allow to select Storage Routers on which the arakoons need to be created.

**Comment by domsj** [comment]
I see another option, in line with (one of) the suggested solution for https://github.com/openvstorage/framework-alba-plugin/issues/177 .
Allow assigning roles to nodes.
The roles could e.g. be
alba_maintenance
alba_nsm_host
alba_abm
alba_maintenance/{backend}
alba_nsm_host/{backend}
alba_abm/{backend}

When creating a new backend the abm/nsm_host/maintenance have to be deployed.
At this time the roles of the nodes could be checked to see where the customer would prefer to run these services.
If {service}/{backend} is not found then do a fallback to {service}. (And if that doesn't exist do whatever is done now already.)
The customer can at a later time add {service}/{backend} roles to nodes at which time (or later during a periodic checkup) the new role division could be taken into account.

**Comment by wimpers** [comment]
After discussion with stakeholders decision was to go for option1 . Create Arakoons in advance and select them while creating the backend. Must be possible to add nsm arakoons afterwards?

**Comment by wimpers** [comment]
This functionality is only exposed in the API (not in the GUI).
When creating a backend you can specify
* abm arakoon
* nsm arakoon: a list of nsm arakoons to use

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
The ALBA Backend creation now allows to specify an ABM cluster and NSM clusters
Either None are provided (than the framework chooses) or both are provided
Example of calling the API:
```
client.post(api='alba/backends', data=json.dumps({'backend_guid': <backend_guid>, 'scaling': 'LOCAL', 'abm_cluster': 'external-abm-cluster-2', 'nsm_clusters': ['external-nsm-cluster-1']}))
```

https://github.com/openvstorage/framework/pull/1453 --> 
https://github.com/openvstorage/framework-alba-plugin/pull/371 -->

**Comment by khenderick** [comment]
openvstorage-backend-1.7.13.1
openvstorage-2.7.13.1
