### ISSUE TITLE
Inconsistent status across backend pages

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#182]
![2016-08-10_16-31-49](https://cloud.githubusercontent.com/assets/8392927/17560134/2d2d626c-5f21-11e6-8c63-049343349a34.png)

Had this issue on my 3 datacenter env. On the list page the geoscale backend is green, on the detail page it is red.

**Comment by wimpers** [comment]
@khenderick can we make sure that both statuses are inline.

**Comment by kvanhijf** [comment]
Was fixed by https://github.com/openvstorage/framework-alba-plugin/issues/210

**Comment by JeffreyDevloo** [comment]
Closing because of the referenced ticket is the real culprit.
