### ISSUE TITLE
Backend detail page hangs in case there is an issue with fetching the details of an ASD node.

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#192]
Backend detail page hangs in case there is an issue with fetching the details of an ASD node.

**Comment by khenderick** [comment]
Do you have some more information, especially what "an issue" is. Is it slow, or is it offline, or is there some error?

**Comment by wimpers** [comment]
@saelbrec was investigating, I believe the proxy was crashing every few minutes.

**Comment by wimpers** [comment]
Workaround:  fix the underlying issue.

**Comment by khenderick** [comment]
Could not reproduce the issue, but found a few minor glitches in the interface which I fixed by #243, packaged in openvstorage-backend-1.7.4-rev.766.0d9f30e

**Comment by wimpers** [comment]
Closed by PM.
