### ISSUE TITLE
Re-enable upgrades

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework-alba-plugin#198]
Re-enable upgrades

**Comment by khenderick** [comment]
Fixed by #197, packaged in openvstorage-backend-1.7.3-rev.689.95a4c61

Please note that the upgrade will work from the above package onwards. Upgrading to that package won't work.

**Comment by JeffreyDevloo** [comment]
In reference to: https://github.com/openvstorage/framework/issues/877
### Test result
Test passed.
