### ISSUE TITLE
ASDManager wrapper should raise on failure

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework-alba-plugin#207]
ASDManager wrapper should raise on failure

**Comment by khenderick** [comment]
Fixed by #208, packaged in openvstorage-backend-1.7.3-rev.702.e25b455

**Comment by JeffreyDevloo** [comment]
### Information
Verifying this based on code. The ASDManager wrapper would only error in normal cases if the asd-manager should fail (and our goal is to make it work).

Instead of returning calls that were unsuccessful, the code will now throw a RunTimeError.

Closing.
