### ISSUE TITLE
framework can't handle arbitrary preset names

### ISSUE THREAD

**Issue by toolslive** [openvstorage/framework-alba-plugin#216]
`kinetic_preset` for example.

**Comment by khenderick** [comment]
Current regex: ```/^[0-9a-zA-Z][a-zA-Z0-9]{1,18}[a-zA-Z0-9]$/```

**Comment by wimpers** [comment]
@toolslive  what does ALBA allow?

I would say a-Z0-9 and - and _ (where - and _ can't be the first character)

**Comment by khenderick** [comment]
@wimpers (BAM), I want to re-raise this ticket.

Recently, the API for creating presets was changed so it enforces the same constraints as the GUI: ```[a-zA-Z0-9]{3,20}```. Before this change, the API allowed everything.

@domsj made the correct remark that this could lead to issues on customer integrations, as they might already pass in other characters (spaces, dashes, special characters, ...).

Should be thus "revert" this and again allow all characters? The GUI must be in sync with the API so changes will be reflected in both.

**Comment by wimpers** [comment]
a-Z0-9 and - and _ (where - and _ can't be the first character)

**Comment by wimpers** [comment]
@grimpy please check from your side if your code would violate this restriction.

**Comment by grimpy** [comment]
No problem for us currently we create then manually

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1275 --> openvstorage-2.7.8-rev.4446.8fa48b9
https://github.com/openvstorage/alba-asdmanager/pull/194 --> openvstorage-sdm-1.6.8-rev.502.8028537
https://github.com/openvstorage/framework-alba-plugin/pull/308 --> openvstorage-backend-1.7.8-rev.883.5dc430d

**Comment by kvanhijf** [comment]
As @wimpers suggested, presets created through GUI and API must now comply to the following rule:
a-zA-Z0-9 and - and _ (where - and _ can't be the first character)

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup cluster
- Tested preset names

#### API code
```
from ci.main import Workflow
from ci.setup.backend import BackendSetup


class PresetTest(object):
    test_names = ['_shouldnotwork_', 's_w', 'should_work', 'should_not_work_']
    backend_name = 'mybackend'
    preset_template = {"name": "mypreset",
                       "compression": "snappy",
                       "encryption": "none",
                       "policies": [[1, 2, 2, 3]],
                       "fragment_size": 2097152}
    @staticmethod
    def test_preset_api():
        workflow = Workflow()
        for index in xrange(1, 3):
            for test_name in PresetTest.test_names:
                if index == 2:
                    test_name = test_name.replace('_', '-')
                preset_details = PresetTest.preset_template
                preset_details['name'] = test_name
                try:
                    BackendSetup.add_preset(albabackend_name=PresetTest.backend_name, preset_details=preset_details, api=workflow.api)
                    print '{0} did work!'.format(test_name)
                except RuntimeError as ex:
                    print '{0} did not work. Got {1}'.format(test_name, ex)

```
### Output
```
_shouldnotwork_ did not work. Got Preset `_shouldnotwork_` has failed to create on backend `mybackend`
s_w did work!
should_work did work!
should_not_work_ did not work. Got Preset `should_not_work_` has failed to create on backend `mybackend`
-shouldnotwork- did not work. Got Preset `-shouldnotwork-` has failed to create on backend `mybackend`
s-w did work!
should-work did work!
should-not-work- did not work. Got Preset `should-not-work-` has failed to create on backend `mybackend`

```

### Test result
Test passed.
