### ISSUE TITLE
Error in NSM scaling logic

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework-alba-plugin#217]
Error in NSM scaling logic. When the code is supposed to automatically scale the NSMs, it just assumes there are enough clusters running and doesn't create new clusters.

**Only fix this when we have the time to write unittests**

**Comment by khenderick** [comment]
As soon as a node is overloaded, the ```min_nsms``` argument is ignored and only one is deployed.

**Comment by khenderick** [comment]
Fixed by #221, packaged in openvstorage-backend-1.7.3-rev.721.b4724e5

**Comment by wimpers** [comment]
Closed by PM.
