### ISSUE TITLE
Statistics (puts/gets per second) are 0 for global backend

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#230]
Statistics (puts/gets per second) are 0 for global backend. 

I currently don't see how we can provide these statistics ( @domsj any idea) so removing them might be a better idea.

**Comment by khenderick** [comment]
We use ```asd-multistatistics``` to fetch the ```multi_get``` and ```apply``` parameters, so it just should work. If it doesn't show then there's either a bug in the Framework or Alba.

So I'd rather just fix the bug?

**Comment by khenderick** [comment]
So we can just gather an sum up the ```asd-multistatistics``` and you will have high numbers. However, I wonder what numbers you actually expect; if you write one object to the backend. Do you want to see 1 put? At this moment - on a local backend - if you write one object with a  8, 5, x, x policy, you might see 13 puts instead.

**Comment by wimpers** [comment]
I believe put and get statistics are becoming meaningless for vpools/backends so I'd rather remove them from the GUI.

With RORA and HPRM we go directly to the ASDs bypassing the proxy (where these values are now aggregated. This means that if we want to provide statistics we need to gather them on an ASD level per namespace. I don't see the benefit of having an aggregate of these gets/puts per vPool or backends as comparison between them is quite meaningless. 

I would in the monitoring keep puts/gets (like they are now) on a proxy level (for support purposes) and on an ASD level keep track of puts/get per ASD across all namespaces on the disk.

**Comment by wimpers** [comment]
Decision is to remove the put/get stats per backend
