### ISSUE TITLE
Integrate alba ctr mode encryption

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework-alba-plugin#270]
In the next alba version CTR mode encryption should be available: https://github.com/openvstorage/alba/pull/444 .

Where it used to say "aes-cbc-256" you can now also specify "aes-ctr-256".

When you have a new enough alba everywhere (all alba components updated to support this feature) it's recommended to use CTR mode for encryption instead of CBC, because it plays along nicer with partial reads (and should be just as secure).

**Comment by wimpers** [comment]
Bam believes this is a small one?

**Comment by khenderick** [comment]
No, since the "when you have a new enough alba everywhere" is not a supported use-case yet. Todo: have this async upgrade stuff in place that can enable/migrate certain features when a set of pre-requirements are met (e.g. version > X on all nodes).

**Comment by wimpers** [comment]
I think we can assume that all nodes will have the newest ALBA and the use case where not all nodes have the new ALBA can be ignored.

**Comment by wimpers** [comment]
Also you can't switch from encryption mode so going from none/cbs to ctr isn't supported.

**Comment by wimpers** [comment]
Basically no need to check if ALBA version is up to date.

**Comment by khenderick** [comment]
Ok, fair enough.

However, to be noted that if a customer updates the framework, and then selects the new encryption method, it will fail.

**Comment by wimpers** [comment]
Ok, noted

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework-alba-plugin/pull/302 --> openvstorage-backend-1.7.8-rev.873.16660bb

@QA: This new encryption method is not yet available until the alba team provides us with a new version
@domsj or @toolslive : ALBA 1.2.5 will contain support for this encryption mode?

@QA: Additional verification logic has been added to our BLL
* Delete preset
** If preset name does not exists, only a warning will be logged
** if the 'is_default' flag is True (provided by alba list-presets), the preset cannot be deleted
* Update preset
** At least 1 policy must be provided
** The rule k <= c <= k + m must apply
** The values in the policy must be integers
** The preset name must exist
* Add preset
** Name must comply to regex '^[0-9a-zA-Z][a-zA-Z0-9]{1,18}[a-zA-Z0-9]$'
** Compression must be 1 of: ['snappy', 'bz2', 'none']
** Encryption must be 1 of: ['aes-cbc-256', 'aes-ctr-256', 'none']
** Fragmentsize must be between 16 bytes and 1 Gib
** Preset name cannot exist already
** Policies provided must comply to same rules as with update_preset

Additional API tests could be generated based on above input

**Comment by domsj** [comment]
@kvanhijf alba 1.3.0 will contain support for the new encryption mode. (if an 1.2.5 were to be released it would be an 1.2.4 plus some extra bugfixes)

regarding preset validation: https://github.com/openvstorage/alba/blob/c6859320fd93597f132c01390dca244746b03004/ocaml/src/preset.ml#L116-L133 that's what alba does

**Comment by pploegaert** [comment]
AT to be created: https://github.com/openvstorage/integrationtests/issues/434

**Comment by JeffreyDevloo** [comment]
Opening as it has not been validated yet.

**Comment by domsj** [comment]
This has been validated on the production environment!
