### ISSUE TITLE
systemd does not restart services that spontaneously stopped

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework-alba-plugin#274]
I did a `pkill alba` on a storage node and the asd/maintenance processes were not restarted by systemd.
This differs from the previous behaviour with upstart (on ubuntu 14.04).
The same problem probably exists for all other services, so you may want to create an equivalent ticket on the framework repo.

**Comment by khenderick** [comment]
Now we have ```Restart=on-failure``` and I think this should be ```Restart=always``` or sth like that.

**Comment by khenderick** [comment]
Reminder to write update logic that can rebuild all service files where required.

**Comment by khenderick** [comment]
Documentation states that usually an ```on-failure``` should be the way to go, and ```always``` isn't the best option. E.g. you won't be able to stop the service by manually terminating it (outside systemd). Is that really what we want?

**Comment by saelbrec** [comment]
We want systemd to restart the processes when it exits with unclean exit code, which is covered by 'on-failure'.
If one wants to cleanly restart them, systemctl commands should be used.
Let's keep the current settings.
