### ISSUE TITLE
Linking LOCAL/GLOBAL backends should watch for 'decommissioned' flag

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework-alba-plugin#280]
Issue:
Unlinking a backend from another backend is successful, but linking the same backend again wont do anything

Cause:
After having unlinked/removed a backend from another backend, we issue a purge-osd command to ALBA
This results in the OSD having a 'decommissioned' flag set to True and this OSD will eventually be removed from the 'list-all-osds' output

Fix:
Now when adding the same backend again, we should check the 'decommissioned' flag. If its set to True, this means this OSD is in the process of being purged and yet to be picked up by the maintenance agents. So as long as this flag is True or the OSD exists at all, we should wait for it in order to re-add it again

@domsj : correct?

**Comment by domsj** [comment]
yes this is correct

**Comment by wimpers** [comment]
When unlinking a backend we should not purge.

**Comment by khenderick** [comment]
@wimpers, how will the data on it be removed in that case?

**Comment by wimpers** [comment]
the idea was now that we don't remove data ( @saelbrec  ) if you unlink a backend

**Comment by wimpers** [comment]
After discussion with the team:
* The purge of the local backend is needed.
* When adding in the GUI, we should display that an purge is ongoing and blocking it.

**Comment by kvanhijf** [comment]
Sidenote: Shouldn't we also mention some warning if any of the presets no longer match? Cause when writing to this backend, a 'NoSatisfiablePolicy' error will be thrown

**Comment by khenderick** [comment]
@kvanhijf, if you mean in the backend detail page? This might be a fairly easy change and imo an interesting feature.

**Comment by kvanhijf** [comment]
Additionally we should also do this for LOCAL backends. When removing ASDs report a warning if none of the presets will be matching anymore.
@wimpers : should we make a separate ticket for this?
Ticket1 (this 1) to make sure that relinking a backend shows a message about the OSD still being deleted
Ticket2 (new 1) to make sure that when any of the presets can be matched when removing OSDs from either a LOCAL or GLOBAL backend, a message/warning is also shown (cause this will be more work and should have a higher priority imo)

**Comment by wimpers** [comment]
@kvanhijf  please create a separate ticket.

**Comment by kvanhijf** [comment]
Issue related to this ticket: https://github.com/openvstorage/framework-alba-plugin/issues/282
This ticket should solely solve the problem about the warning shown when the Backend OSD is still being purged. This ticket should NOT solve the issue about showing a warning when the presets are no longer matched (See linked ticket for this)

**Comment by kvanhijf** [comment]
Issue was fixed by https://github.com/openvstorage/framework-alba-plugin/issues/292
@QA: Unlink a backend from a GLOBAL backend and link it again right away. A warning should pop up satting that the previously linked backend is still being removed
