### ISSUE TITLE
Unlinking Backends and removing ASDs should show warning about unmatching presets

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework-alba-plugin#282]
We should make sure that when any of the presets can no longer be matched when removing OSDs from either a LOCAL or GLOBAL backend a message/warning is shown

In the current state, we always allow this, but this could result in a backend which doesn't allow the customer to write to anymore.

**Comment by wimpers** [comment]
The same holds fro removing nodes see https://github.com/openvstorage/framework/issues/1349

**Comment by kvanhijf** [comment]
openvstorage-2.8.2-dev.1493016604.db35478
openvstorage-backend-1.8.2-dev.1493016700.8a81996

**Comment by khenderick** [comment]
Packaged in 1.9.0
