### ISSUE TITLE
Allow to add nsm arakoon to a backend (api)

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#284]
This is an extension of https://github.com/openvstorage/framework-alba-plugin/issues/178. In the API we should have an option to add a nsm arakoon to a backend in the case the cluster is using externally managed arakoons.

**Comment by wimpers** [comment]
The arakoon cluster itself should not be setup by OVS. This ticket is about the claiming of that cluster for a certain backend.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1359 --> 
https://github.com/openvstorage/alba-asdmanager/pull/208 --> 
https://github.com/openvstorage/framework-alba-plugin/pull/338 -->

**Comment by kvanhijf** [comment]
@openvstorage/qa :

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-backend-1.7.10.1

**Comment by pploegaert** [comment]
https://github.com/openvstorage/integrationtests/issues/444
