### ISSUE TITLE
Integrate alba/issues/516

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#312]
Integrate https://github.com/openvstorage/alba/issues/516 in the framework
* Make sure the restriction (k <= c) is removed in the API 

Keep the restriction in the GUI

**Comment by khenderick** [comment]
To be clear on this: it means that we allow customers to create presets with policies that will acknowledge the write even though not all required data is written. This means a power failure might lead to data-loss when it is not expected. Is this what we want, @wimpers?

**Comment by wimpers** [comment]
Yes,  a customer absolutely wants this.

**Comment by wimpers** [comment]
Customer is aware of the possible dataloss.

**Comment by wimpers** [comment]
After discussion with stakeholders. Only remove the restriction in the API. GUI can keep the  restriction for safety.

**Comment by wimpers** [comment]
After discussion with stakeholders: don't remove the restriction at all.

**Comment by khenderick** [comment]
Closed as it doesn't make sense to validate something that didn't change.
