### ISSUE TITLE
Backwards incompatibility for abm/nsm config location

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework-alba-plugin#313]
Backwards incompatibility for abm/nsm config location

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1292 --> openvstorage-2.7.8-fargo.2
https://github.com/openvstorage/framework/pull/1293 --> openvstorage-2.7.9-rev.4463.0761b63
https://github.com/openvstorage/framework-alba-plugin/pull/316 --> openvstorage-backend-1.7.8-fargo.2
https://github.com/openvstorage/framework-alba-plugin/pull/317 --> openvstorage-backend-1.7.9-rev.892.1c0e688

No issue could be reproduced regarding incompatibility of NSM/ABM config location
However, we did find out another update issue related to post-update actions. Now they're executed making use of our 'remote' module (running in a new process, thus executing the new code)
