### ISSUE TITLE
Failed removing disk /dev/sdb: 'NoneType' object has no attribute 'partitions'

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#315]
Initialized  an SSD  with 2 ASD and a bit later removed it. Didn't claim the ASDs.

Resulting error:
Failed removing disk /dev/sdb: 'NoneType' object has no attribute 'partitions'

**Comment by wimpers** [comment]
Workaround, claim the ads and next you can remove it.

**Comment by wimpers** [comment]
please reproduce and if possible add to RC3

**Comment by kvanhijf** [comment]
@wimpers , @pploegaert : I couldn't reproduce this issue just now
Tried reproducing using an SSD and a HDD with 1 or more unclaimed ASDs
Also tried reproducing starting from an SSD without filesystem and with filesystem, but all to no avail

Guess this can be closed due to lack of evidence?
