### ISSUE TITLE
Sorting issue on backend page with solely asd-managers and storagerouters

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#326]
### Problem description

![gifrecord_2017-01-06_101504](https://cloud.githubusercontent.com/assets/17570109/21713357/e520d262-d3f9-11e6-8e71-a17af001dee7.gif)

**Comment by khenderick** [comment]
Fixed in #327
Dev package: openvstorage-backend-1.7.9-dev.1483716781.891547f

**Comment by khenderick** [comment]
openvstorage-backend-1.7.9.1

**Comment by JeffreyDevloo** [comment]
### Steps
- Updated the environment 
- Did not see the issue anymore

### Test result
Test passed.
