### ISSUE TITLE
Backend with no storage nodes is in failure

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework-alba-plugin#335]
We've observed an issue on our development environment: 
- The setup is hyperscale
- We have no storagenodes
- We've created a backend
- Our backend was in failure

![](http://i.imgur.com/Dtg3uGt.png)

**Comment by khenderick** [comment]
Should be warning, not failure

**Comment by khenderick** [comment]
Fixed by #337, packaged on dev in openvstorage-backend-1.7.10-dev.1484821309.0e04b12

**Comment by kvanhijf** [comment]
@openvstorage/qa : openvstorage-backend-1.7.10.1
