### ISSUE TITLE
Investigate possible slower backend pages

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework-alba-plugin#344]
Investigate possible slower:
* backend overview
* backend detail page

**Comment by khenderick** [comment]
The recently added `live_status` field which basically generates a status based on backend installation state, disk state, maintenance service states, ... is relatively slow (250-400ms) because it needs to get all maintenance services for every node to count whether there are enough maintenance services for that particular backend. This 250-400ms ish number adds up if there are quite some backends on the environment, especially since it's used on the overview page.

**Comment by khenderick** [comment]
I think the only reasonable solution in making such pages faster again is (re)introducing progressive loading of data. There is simply too much (slower) data to be loaded in a single query. Imo it makes more sense to divide all data to be shown into sections based on their expected load time, and execute a query foreach section.

**Comment by wimpers** [comment]
I would add progressive loading for the backend status on the overview page only.

**Comment by khenderick** [comment]
Fixed by https://github.com/openvstorage/framework/pull/1388 and #349, packaged on dev in openvstorage-2.7.11-dev.1485871045.c621478 and openvstorage-backend-1.7.11-dev.1485871129.dd74d13

**Comment by khenderick** [comment]
openvstorage-backend-1.7.11.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/452

**Comment by JeffreyDevloo** [comment]
We should manufacture an overall data traffic tester with response times.
However we are currently tackling on testing bigger features so I'm closing it down (for now)
