### ISSUE TITLE
Manually add asds iso relying on multicasts

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework-alba-plugin#378]
Due to possible network related issues with multicasts, it would be interesting to add asds manually so alba doesn't have to discover them first. This will also remove our dependency on the maintenance processes for discovery etc.

@domsj, do you see any changes required for Alba?

**Comment by khenderick** [comment]
@domsj, another question; can we somehow ask an ASD whether it's claimed by any backend, and if so by which one? Without relying on these multicast messages.

**Comment by khenderick** [comment]
Related to openvstorage/alba#582

**Comment by domsj** [comment]
@khenderick I think everything is there from the alba side to be able to add asds to the albamgr, use `alba add-osd (--help)`.

For discovering if it's already claimed by a backend ... we could add an extra command for that.

(Or you could add the asd to the albamgr using add-osd, and then do a list-osds afterwards, that should also give you this info... but then you might be needlessly polluting an abm)

**Comment by khenderick** [comment]
@domsj, if it isn't much work, I'd rather have a command that connects directly to the ASD to see whether it has been claimed by a backend. Just trying to add it to a backend as a "test" seems kinda dirty. Would this be a lot of work for you?

**Comment by domsj** [comment]
It's not a lot of work. Maybe a couple of hours. I've created a ticket on the alba repo.
When would you like this?

**Comment by khenderick** [comment]
I'd like to have this by the time I need to solve this ticket. @wimpers, @saelbrec, any idea when this ticket needs to be solved?

**Comment by wimpers** [comment]
@domsj will pick it up by end of the week between soup and potatos

**Comment by kvanhijf** [comment]
@domsj : Please provide framework team with input once implemented

**Comment by khenderick** [comment]
Available in alba 1.3.7

**Comment by khenderick** [comment]
* Requirement: https://github.com/openvstorage/alba-asdmanager/issues/231

**Comment by domsj** [comment]
Once you go down this path, also do this:
- disable sending multicast messages from the asds, see https://github.com/openvstorage/alba/pull/677/files#diff-d1c9a376c7ab6525cade8967a0d5982aR31
- tell maintenance to not listen for multicast messages, see https://github.com/openvstorage/alba/pull/677/files#diff-f488e8533660f9152198015c671a715cR20

**Comment by wimpers** [comment]
Since https://github.com/openvstorage/alba-asdmanager/issues/231 has landed, we can pick up this one.

**Comment by wimpers** [comment]
I assume this means 
- re-introducing the ADD button on the ALBA backend page which asks for IP, Login, Passwd, chassis type
- looping over the different disks and adding the detected OSDs to the DB
- allowing to claim the disks (initialize isn't required?)
- decommission an OSD

**Comment by khenderick** [comment]
No, this ticket is about manually adding an ASD and is not related to anything related to storage nodes.

**Comment by wimpers** [comment]
Please make sure to add the node_id when adding the asd

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/alba-asdmanager/pull/260
Packaged in: 2.10.0-dev.1502714381.9319ff7-1
