### ISSUE TITLE
Revive the Kinetic support

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#415]
Reviving the Kinetic protocol support for the framework alba plugin so Kinetic drives can be used like regular drives.

Required for this ticket are
- https://github.com/openvstorage/framework-alba-plugin/issues/378
- https://github.com/openvstorage/framework-alba-plugin/issues/414

**Comment by wimpers** [comment]
Please make sure we can extract the same data/info as from a normal ASD

**Comment by khenderick** [comment]
First set of tasks, based on specs on 27/06.

* [ ] Add `AD` as type to `AlbaOSD`.
* [ ] A `GENERIC` type should also be added to `AlbaNode`, that's merely a container for individual OSDs .(limit to ADs only?). In the future, we can then also add extra types once more chassis need to be supported.
* [ ] An `AlbaNode` should load a different client based on its type. Preferably loaded through some factory.
* [ ] Re-introduce the possibility to manually add `AlbaNode`s by a wizard without discovery. The best would be to use the same wizard as is used now, prefilled in case of a "discovered" node.
* [ ] A `GENERIC` `AlbaNode` should have (at least) a `name` and a `node_id`.
* [ ] Allow to add OSDs to this node. Again, we can use some kind of generic wizard here so we could in theory also add `ASD`s. Node that this is _not_ setting up `ASD`s, but just adding them (that is, asking for the ip and port etc).
* [ ] Use as much as the possible the same styling for `AD`s and `ASDs`.
* [ ] Prevent an already in use `AD` (or `ASD`) to be added.
* [ ] Execute an `InstanceSecureErase` or whatever is available when an `AD` is added.
* [ ] Execute the same when it's removed again.
* [ ] Make the `AlbaNode`s collapsable in the GUI (by default), however, show their health in the collapsed view (this means it most likely won't be any faster).

**Comment by wimpers** [comment]
After discussion:

* [ ] Req - 4h - Add `AD` as type to `AlbaOSD`.
* [ ] Req - 1w - Fake ALBA disk relation
* [ ] Req - 1w - A `GENERIC` type should also be added to `AlbaNode`, that's merely a container for individual OSDs (limit to ADs only?). In the future, we can then also add extra types once more chassis need to be supported. An `AlbaNode` should load a different client based on its type. Preferably loaded through some factory.
* [ ] Req - 1w - Re-introduce the possibility to manually add `AlbaNode`s by a wizard without discovery. The best would be to use the same wizard as is used now, prefilled in case of a "discovered" node. A `GENERIC` `AlbaNode` should have (at least) a `name` and a `node_id`.
* [ ] Req - 3d - Allow to add OSDs to this node through API
* [ ] Opt - 3d - Use as much as the possible the same styling for `AD`s and `ASDs` (including stats etc)
* [ ] Opt - 2d - Make the `AlbaNode`s collapsable in the GUI (by default), however, show their health in the collapsed view (this means it most likely won't be any faster).
* [ ] Opt - 2w - Testing

**Comment by khenderick** [comment]
Few dependencies:
* openvstorage/alba#749
* openvstorage/alba#748

**Comment by kvanhijf** [comment]
All related PRs:

https://github.com/openvstorage/framework/pull/1702
https://github.com/openvstorage/iscsi-manager/pull/12
https://github.com/openvstorage/alba-asdmanager/pull/260
https://github.com/openvstorage/framework-extensions/pull/12
https://github.com/openvstorage/framework-alba-plugin/pull/432

**Comment by JeffreyDevloo** [comment]
More related PRs:

https://github.com/openvstorage/framework-alba-plugin/pull/440
https://github.com/openvstorage/framework-alba-plugin/pull/441
https://github.com/openvstorage/framework-alba-plugin/pull/442
https://github.com/openvstorage/framework-alba-plugin/pull/443
https://github.com/openvstorage/framework-extensions/pull/18
https://github.com/openvstorage/framework-extensions/pull/19
https://github.com/openvstorage/iscsi-manager/pull/19
https://github.com/openvstorage/framework/pull/1718

Initial release packaged in: 2.10.0-dev.1502714381.9319ff7-1
