### ISSUE TITLE
JSON output of download-object is not returned using AlbaCLI

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework-alba-plugin#438]
For some mysterious reason, the JSON output of a download-object call returns an empty list.

The outputs from OVS shell:

In [70]: AlbaCLI.run('download-object', config=abmconfig, extra_params=[space['name'], o, downloadpath], to_json=True)
Out[70]: {}

In [71]: AlbaCLI.run('download-object', config=abmconfig, extra_params=[space['name'], o, downloadpath], to_json=False)
Out[71]: 'object tlog_3a76bddd-764b-4e5e-9103-166702bd39f1 with size 1072 downloaded to file /tmp/mekker\n'

The outputs when using the regular CLI:

alba download-object --config arakoon://config/ovs/vpools/9f24c8b5-d776-40d5-a371-e14c6f4a6faa/proxies/a2036aae-2985-4a4d-b491-c07b374141b4/config/abm?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini 001cb6d8-1cf8-49c8-868e-678c4e4120ba tlog_3a76bddd-764b-4e5e-9103-166702bd39f1 /tmp/mekker --to-json
*SNIP*
2017-07-28 08:41:29 808673 -0400 - NY1SRV0008 - 21343/0000 - alba/cli - 210 - info - connect_with : 172.17.0.61 8607 None Net_fd.TCP (fd:196)
2017-07-28 08:41:29 808712 -0400 - NY1SRV0008 - 21343/0000 - alba/cli - 211 - info - connect_with : 172.17.0.72 8606 None Net_fd.TCP (fd:197)
{ "success": true, "result": {} }

root@NY1SRV0008:~# alba download-object --config arakoon://config/ovs/vpools/9f24c8b5-d776-40d5-a371-e14c6f4a6faa/proxies/a2036aae-2985-4a4d-b491-c07b374141b4/config/abm?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini 001cb6d8-1cf8-49c8-868e-678c4e4120ba tlog_3a76bddd-764b-4e5e-9103-166702bd39f1 /tmp/mekker
*SNIP*
object tlog_3a76bddd-764b-4e5e-9103-166702bd39f1 with size 1072 downloaded to file /tmp/mekker

**Comment by kvanhijf** [comment]
@jtorreke Shouldn't this have been created in the Alba repository?
Since on CLI you're seeing the same empty result as you do when using the AlbaCLI, so i'm guessing the issue lies in the Alba code, not in our wrapper.

**Comment by jtorreke** [comment]
I guess we can close this as a user error. Thanks for clarifying @kvanhijf and @domsj
