### ISSUE TITLE
backend detail page is horribly slow

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework-alba-plugin#439]
See nuvolat env ny1 for an example.
Sometimes it fails to load, other times it takes more than a minute.

**Comment by JeffreyDevloo** [comment]
Had to bump the call timeout back to 5 minutes instead of 30s to actually load after a while.
Saw that certain dynamics are having a hard time to get computed.

**Comment by JeffreyDevloo** [comment]
Further looking into as it is quite important to have it fixed.
![selection_043](https://user-images.githubusercontent.com/17570109/28919371-7d52566c-784d-11e7-8785-d754c427d666.png)
Seems like local_stack and local_summary are currently causing some issues. Further looking into it.

**Comment by JeffreyDevloo** [comment]
Calls towards the asd-manager took over 40s for certain asd-managers. Restarting the asd-manager has patched the issue for now.
Need to look into the reason why the response times were that high.

**Comment by JeffreyDevloo** [comment]
I have the feeling the swapiness nature of the vms hosting the asd-manager has something to do with it.

**Comment by JeffreyDevloo** [comment]
More an issue for here: https://github.com/openvstorage/alba-asdmanager/issues/272
