### ISSUE TITLE
Maintenance read preference for global backends is not correct

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework-alba-plugin#452]
As discussed with @kvanhijf, the read preference should have node_id(s) of the relevant local backend(s), similar to how read preference is filled in for the alba proxies belonging to a global backend.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/alba-asdmanager/pull/298
https://github.com/openvstorage/framework-alba-plugin/pull/518

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.11.0 release
