### ISSUE TITLE
alba asd warning after shutdown all node and start all node

### ISSUE THREAD

**Issue by hoanhdo** [openvstorage/framework-alba-plugin#478]
Hi all.

I testing failover for my cluster.
after shutdown all node and start server (use shutdown -h now)
This is warning status
![selection_090](https://user-images.githubusercontent.com/5550425/30508963-1345ea9c-9ace-11e7-8e01-2777ffce64d7.png)
![selection_091](https://user-images.githubusercontent.com/5550425/30508964-134641f4-9ace-11e7-809b-76580d51e41b.png).

I tried resstart asd but not working.
I check service on nodes . they running.

> alba-asd-ncaN3UaO8axPb1rcolUJqdh9akaPJIct.service - ALBA ASD
>    Loaded: loaded (/lib/systemd/system/alba-asd-ncaN3UaO8axPb1rcolUJqdh9akaPJIct.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sat 2017-09-16 10:20:03 ICT; 45min ago
>  Main PID: 28566 (alba)
>     Tasks: 7
>    Memory: 22.0M
>       CPU: 796ms
>    CGroup: /system.slice/alba-asd-ncaN3UaO8axPb1rcolUJqdh9akaPJIct.service
>            └─28566 /usr/bin/alba asd-start --config arakoon://config/ovs/alba/asds/ncaN3UaO8axPb1rcolUJqdh9akaPJIct/config?ini=%2Fopt%2Fasd-manager
> 
> Sep 16 11:05:24 ovs-r1-performance-2 alba[28566]: 2017-09-16 11:05:24 210871 +0700 - ovs-r1-performance-2 - 28566/0000 - alba/asd - 646 - info - se
> Sep 16 11:05:24 ovs-r1-performance-2 alba[28566]: 2017-09-16 11:05:24 211045 +0700 - ovs-r1-performance-2 - 28566/0000 - alba/asd - 647 - info - se

> 
> ● alba-asd-UK5a6IC1F79oy2p74ao0MwBMz6cUGGFT.service - ALBA ASD
>    Loaded: loaded (/lib/systemd/system/alba-asd-UK5a6IC1F79oy2p74ao0MwBMz6cUGGFT.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sat 2017-09-16 10:20:02 ICT; 45min ago
>  Main PID: 28400 (alba)
>     Tasks: 7
>    Memory: 18.5M
>       CPU: 791ms
>    CGroup: /system.slice/alba-asd-UK5a6IC1F79oy2p74ao0MwBMz6cUGGFT.service
>            └─28400 /usr/bin/alba asd-start --config arakoon://config/ovs/alba/asds/UK5a6IC1F79oy2p74ao0MwBMz6cUGGFT/config?ini=%2Fopt%2Fasd-manager
> 
> Sep 16 11:05:18 ovs-r1-performance-2 alba[28400]: 2017-09-16 11:05:18 343572 +0700 - ovs-r1-performance-2 - 28400/0000 - alba/asd - 645 - info - se
> Sep 16 11:05:18 ovs-r1-performance-2 alba[28400]: 2017-09-16 11:05:18 343734 +0700 - ovs-r1-performance-2 - 28400/0000 - alba/asd - 646 - info - se

> 
> ● alba-asd-Ql9ufzfkyd4VbUKfHVLNdfanOrsgqhF9.service - ALBA ASD
>    Loaded: loaded (/lib/systemd/system/alba-asd-Ql9ufzfkyd4VbUKfHVLNdfanOrsgqhF9.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sat 2017-09-16 10:20:05 ICT; 45min ago
>   Process: 28726 ExecStartPre=/bin/sh -c if [ ! -d /opt/asd-manager/run ]; then mkdir /opt/asd-manager/run; chown alba:alba /opt/asd-manager/run; f
>  Main PID: 28749 (alba)
>     Tasks: 6
>    Memory: 19.6M
>       CPU: 770ms
>    CGroup: /system.slice/alba-asd-Ql9ufzfkyd4VbUKfHVLNdfanOrsgqhF9.service
> 

How can i fix this warning.
Thanks

**Comment by JeffreyDevloo** [comment]
Hi Hoanhdo

The asd have had recent errors due to the shutdown. To resolve this, you should just have some IO again on those asds.

**Comment by hoanhdo** [comment]
Hi JeffreyDevloo 
It work.

Thanks
