### ISSUE TITLE
[Active Drive] Preset availability is being calculated on available osds, not claimed ones

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#482]
### Problem description
My current backends osds:
![image](https://user-images.githubusercontent.com/17570109/30582277-6bff9d02-9d23-11e7-8381-4a55e1317fb0.png)
The preset is available (became available after allocating osds to the slots)
![image](https://user-images.githubusercontent.com/17570109/30582283-72d65a1c-9d23-11e7-8528-d5bcf71c96ae.png)
The problem is that this preset will not be satisfied as no osds are attached to this backend, giving the user a wrong view of reality

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework-alba-plugin/pull/493 -->

**Comment by kvanhijf** [comment]
Simply creating (without claiming) 3 ASDs on a backend with default presets already showed this issue.
Preset 2,2,3,4 became available.
Fixed now by checking in the 'presets' dynamic whether the ASD has actually been claimed by current Backend

**Comment by kvanhijf** [comment]
Included in release https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.10.1
