### ISSUE TITLE
Add more logging when the backend would be marked as 'failure'

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#485]
### Problem description
Debugging as to why a backend is in failure state can be troublesome, especially if it happens periodically
There are a number of reason why it can be in failure and half of these reasons are not logged.

**Comment by wimpers** [comment]
@JeffreyDevloo do you have an idea how much work this would be ? Is this a small one that @simonOpenV could pick up?

**Comment by JeffreyDevloo** [comment]
@wimpers 
This is a small fix that Simon could pick up
I estimate it to be an hour of work

**Comment by simonOpenV** [comment]
Fixed in #549 
Packaging info: openvstorage-backend-core_1.11.0-dev.1516281611.6affa3c-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.11.0 release
