### ISSUE TITLE
Local summary 'gray' could result into a keyerror with global backends

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#494]
## Problem description
The current implementation of local summary requires a key 'gray' within the devices of a remote stack

When having a global backend which is using local backends from a different cluster, this key might not be returned.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework-alba-plugin/pull/495 -->

**Comment by kvanhijf** [comment]
Included in release https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.10.1
