### ISSUE TITLE
Updater doesn't 'see' updates anymore when services need a restart

### ISSUE THREAD

**Issue by kvanhijf** [openvstorage/framework-alba-plugin#513]
Related issue: https://github.com/openvstorage/framework/issues/1833

**Comment by kvanhijf** [comment]
openvstorage-backend-1.11.0-dev.1507883499.2f5aea1

**Comment by kvanhijf** [comment]
Merging in the code closed it automatically?? Strange

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.11.0 release
