### ISSUE TITLE
Add a "to_json=False" parameter to AlbaCLI.run()

### ISSUE THREAD

**Issue by ovstmoens** [openvstorage/framework-alba-plugin#519]
AlbaCLI.run() always adds the "--to-json" parameter to Alba commands, yet not all Alba commands support it. Please add the possibility to run Alba commands without "to-json", for example by passing a "to_json=False" parameter to the function.

**Comment by JeffreyDevloo** [comment]
Will be fixed by: https://github.com/openvstorage/framework-alba-plugin/pull/525

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.11.0 release
