### ISSUE TITLE
error claim disk to local backend linked to global backend

### ISSUE THREAD

**Issue by hoanhdo** [openvstorage/framework-alba-plugin#575]
Hi all.

I install my cluster on OpenVStorage version : fargo-update-1

> 
> ii  openvstorage                         2.9.5-1                                    amd64        openvStorage
> ii  openvstorage-backend                 1.9.1-1                                    amd64        openvStorage Backend plugin
> ii  openvstorage-backend-core            1.9.1-1                                    amd64        openvStorage Backend plugin core
> ii  openvstorage-backend-webapps         1.9.1-1                                    amd64        openvStorage Backend plugin Web Applications
> ii  openvstorage-core                    2.9.5-1                                    amd64        openvStorage core
> ii  openvstorage-webapps                 2.9.5-1                                    amd64        openvStorage Web Applications

After add peformance node 1,2 and 3, i add node 4 5. 
All disk on node performance 4,5 initialized , but click to claim all disk it do nothing.
I tried remove node, add new nodes but not work.

Thanks.

**Comment by JeffreyDevloo** [comment]
Hello hoanhdo

Is it possible that you can send me the error message contained within the logs? These can retrieved using journalctl -u ovs-workers and journalctl -u ovs-webapp-api

**Comment by hoanhdo** [comment]
This is my logs.
[ovs-workers.log](https://github.com/openvstorage/framework-alba-plugin/files/1750230/ovs-workers.log)
[ovs-webapp-api.log](https://github.com/openvstorage/framework-alba-plugin/files/1750231/ovs-webapp-api.log)

**Comment by wimpers** [comment]
Hi @hoanhdo , 

is this still an issue or did you manage to get this fixed?

**Comment by hoanhdo** [comment]
@wimpers it still an issue. I tried fix but no luck.

**Comment by wimpers** [comment]
Closing this one down as we didn't receive any logs. Re-open if needed or if it can be reproduced.
