### ISSUE TITLE
NBD devices created for iSCSI can be used for ALBA

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#588]
NBD devices created by us for iSCSI can be used for ALBA, this should not be possible.

**Comment by JeffreyDevloo** [comment]
Infinite storage cycle? :+1:

**Comment by wimpers** [comment]
I'm wondering if we don't need to be more clever about this an revisit our strategy:
* we keep on bumping into disks which should not be shown or are not shown
* Amazon EBS disks don't work all together

**Comment by JeffreyDevloo** [comment]
We process the disks that the OS can see. Certain types of drive are ignored already, however we cannot be up to date with all the new hot and flashy stuff...

**Comment by wimpers** [comment]
After discussion with the framework team:
* I this ticket we will do a quick fix by out all NBD disks.
* A feature request should be created to handle this more intelligent (f.e. option to show all block devices, custom filtering).

**Comment by simonOpenV** [comment]
### Will be fixed by: 
https://github.com/openvstorage/alba-asdmanager/pull/328

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.12.0
Packaged in openvstorage-backend-core_1.12.0-1_amd64.deb
