### ISSUE TITLE
Change default cache eviction from LRU to random

### ISSUE THREAD

**Issue by wimpers** [openvstorage/framework-alba-plugin#589]
Change default cache eviction from LRU to random.
Don't setup Redis also.

@JeffreyDevloo

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework-alba-plugin/pull/590
Released in https://github.com/openvstorage/framework-alba-plugin/releases/tag/1.12.0
Packaged in openvstorage-backend-core_1.12.0-1_amd64.deb
