### ISSUE TITLE
Retrieving asd-multistastics is currently done in sync

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework-alba-plugin#600]
### Enhancement description
By specifying a comma separated list of long-ids in the --long-id section of asd-multistatistics, the information is retrieved in sync (for id in long_id).
By specifying --all this would be done in one go which is cheaper.

**Comment by sjovdnbos** [comment]
Should be fixed by this?
https://github.com/openvstorage/framework-alba-plugin/pull/628

**Comment by sjovdnbos** [comment]
### Fixed by:
https://github.com/openvstorage/framework-alba-plugin/pull/625
